smtp_password: ''
smtp_on: true
smtp_host: mail
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_username: ''
smtp_from: ''
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_debugging: false
